/**
 * WiFi Management System for QRTunai Drive Thru
 * Handles automatic password generation, Orbit H2 integration, and WiFi access control
 */

import { addDays, format, isAfter, isBefore } from 'date-fns';

export interface WiFiCredentials {
  ssid: string;
  password: string;
  expiry: Date;
  generatedAt: Date;
  isActive: boolean;
  type: 'daily' | 'hourly' | 'static';
}

export interface SmartQRData {
  // Existing transaction data
  transactionId: string;
  tokenId: string;
  timestamp: string;
  
  // WiFi data
  wifi: {
    ssid: string;
    password: string;
    expiry: string;
    bandwidth: string;
    timeLimit: number; // minutes
    autoGenerated: boolean;
  };
  
  // Metadata
  type: 'transaction_with_wifi';
  version: '2.0';
  url: string;
}

export interface RouterStatus {
  online: boolean;
  lastChecked: Date;
  ip: string;
  connectedDevices?: number;
  error?: string;
}

export class WiFiManager {
  private static readonly GUEST_SSID = 'QRTunai_Guest';
  private static readonly ROUTER_IP = '192.168.8.1';
  private static readonly SESSION_TIMEOUT = 10; // minutes
  
  /**
   * Generate daily password based on current date
   */
  static generateDailyPassword(): string {
    const today = new Date();
    const dateString = format(today, 'MMdd'); // Format: 0115
    return `QR${dateString}`;
  }
  
  /**
   * Generate hourly password for extra security
   */
  static generateHourlyPassword(): string {
    const now = new Date();
    const hour = format(now, 'HH');
    const date = format(now, 'MMdd');
    return `QR${date}${hour}`;
  }
  
  /**
   * Generate WiFi credentials for QR code
   */
  static generateCredentials(type: 'daily' | 'hourly' = 'daily'): WiFiCredentials {
    const now = new Date();
    const password = type === 'daily' 
      ? this.generateDailyPassword()
      : this.generateHourlyPassword();
    
    const expiry = type === 'daily'
      ? addDays(now, 1) // Expire tomorrow
      : new Date(now.getTime() + 60 * 60 * 1000); // Expire in 1 hour
    
    return {
      ssid: this.GUEST_SSID,
      password,
      expiry,
      generatedAt: now,
      isActive: true,
      type
    };
  }
  
  /**
   * Create Smart QR data with WiFi credentials
   */
  static createSmartQRData(transactionId: string, tokenId: string): SmartQRData {
    const credentials = this.generateCredentials('daily');
    const now = new Date();
    
    return {
      transactionId,
      tokenId,
      timestamp: now.toISOString(),
      wifi: {
        ssid: credentials.ssid,
        password: credentials.password,
        expiry: credentials.expiry.toISOString(),
        bandwidth: '2Mbps',
        timeLimit: this.SESSION_TIMEOUT,
        autoGenerated: true
      },
      type: 'transaction_with_wifi',
      version: '2.0',
      url: `${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/t/${tokenId}/form`
    };
  }
  
  /**
   * Validate if WiFi credentials are still valid
   */
  static isCredentialsValid(credentials: WiFiCredentials): boolean {
    const now = new Date();
    return credentials.isActive && isAfter(credentials.expiry, now);
  }
  
  /**
   * Get current active credentials
   */
  static getCurrentCredentials(): WiFiCredentials {
    // In production, this would fetch from database
    // For now, generate based on current time
    return this.generateCredentials('daily');
  }
  
  /**
   * Check if customer needs WiFi access
   */
  static async detectInternetNeed(): Promise<boolean> {
    try {
      // Check if browser is online
      if (!navigator.onLine) {
        return true;
      }
      
      // Test connection speed/quality
      const startTime = Date.now();
      const response = await fetch('/api/connection-test', { 
        cache: 'no-cache',
        signal: AbortSignal.timeout(5000) 
      });
      
      const loadTime = Date.now() - startTime;
      
      // If connection is slow (>3 seconds), suggest WiFi
      return loadTime > 3000 || !response.ok;
      
    } catch (error) {
      // If connection test fails, customer needs WiFi
      return true;
    }
  }
  
  /**
   * Format credentials for display
   */
  static formatCredentialsForDisplay(credentials: WiFiCredentials) {
    return {
      networkName: credentials.ssid,
      password: credentials.password,
      validUntil: format(credentials.expiry, 'HH:mm dd/MM/yyyy'),
      timeLimit: `${this.SESSION_TIMEOUT} menit`,
      instructions: [
        '1. Buka WiFi settings di HP Anda',
        `2. Pilih network "${credentials.ssid}"`,
        `3. Masukkan password: ${credentials.password}`,
        '4. Tunggu connected, lalu kembali ke form'
      ]
    };
  }
  
  /**
   * Generate staff instructions for router management
   */
  static generateStaffInstructions(credentials: WiFiCredentials) {
    return {
      routerIP: this.ROUTER_IP,
      currentPassword: credentials.password,
      updateInstructions: [
        `1. Buka browser → http://${this.ROUTER_IP}`,
        '2. Login dengan admin credentials',
        '3. Navigate ke WiFi Settings → Guest Network',
        `4. Update password guest network: ${credentials.password}`,
        '5. Set time limit: 10 minutes per device',
        '6. Save settings'
      ],
      nextUpdate: format(credentials.expiry, 'dd/MM/yyyy HH:mm'),
      automationNote: 'Password akan diupdate otomatis oleh sistem'
    };
  }
}

/**
 * Connection quality assessment
 */
export class ConnectionQuality {
  static async assess(): Promise<'good' | 'slow' | 'poor' | 'no-internet'> {
    try {
      if (!navigator.onLine) {
        return 'no-internet';
      }
      
      const startTime = Date.now();
      const testPromise = fetch('/api/connection-test', { 
        cache: 'no-cache' 
      });
      
      const timeoutPromise = new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error('timeout')), 5000)
      );
      
      await Promise.race([testPromise, timeoutPromise]);
      const loadTime = Date.now() - startTime;
      
      if (loadTime < 1000) return 'good';
      if (loadTime < 3000) return 'slow';
      return 'poor';
      
    } catch (error) {
      return 'no-internet';
    }
  }
  
  static getRecommendation(quality: string): string {
    switch (quality) {
      case 'good':
        return 'Koneksi internet Anda bagus. Silakan lanjut dengan transaksi.';
      case 'slow':
        return 'Koneksi internet Anda agak lambat. Anda bisa menggunakan WiFi gratis kami untuk pengalaman yang lebih baik.';
      case 'poor':
        return 'Koneksi internet Anda kurang stabil. Sangat disarankan menggunakan WiFi gratis kami.';
      case 'no-internet':
        return 'Tidak terdeteksi koneksi internet. Silakan gunakan WiFi gratis kami untuk melanjutkan transaksi.';
      default:
        return 'Silakan gunakan WiFi gratis kami untuk pengalaman terbaik.';
    }
  }
}

/**
 * Usage tracking and analytics
 */
export class WiFiAnalytics {
  static async logConnection(data: {
    transactionId: string;
    deviceInfo?: string;
    connectionTime: Date;
    sessionDuration?: number;
  }) {
    try {
      // In production, send to analytics service
      console.log('WiFi Connection Logged:', data);
      
      // Could integrate with Google Analytics, Mixpanel, etc.
      if (typeof window !== 'undefined' && 'gtag' in window) {
        (window as any).gtag('event', 'wifi_connection', {
          transaction_id: data.transactionId,
          session_duration: data.sessionDuration || 0
        });
      }
    } catch (error) {
      console.error('Failed to log WiFi analytics:', error);
    }
  }
  
  static async generateDailyReport() {
    const today = format(new Date(), 'yyyy-MM-dd');
    
    // Mock data - in production, fetch from database
    return {
      date: today,
      totalConnections: Math.floor(Math.random() * 50) + 10,
      averageSessionTime: Math.floor(Math.random() * 8) + 5, // minutes
      peakUsageHour: Math.floor(Math.random() * 12) + 9, // 9 AM - 9 PM
      bandwidthUsage: Math.floor(Math.random() * 1000) + 500, // MB
      topDeviceTypes: ['Android', 'iPhone', 'Windows'],
      connectionSuccess: 95 + Math.random() * 5 // 95-100%
    };
  }
}